# Generated by Django 6.0.7 on 2026-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Approval_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
