# Generated by Django 6.0.7 on 2026-07-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='breastfeeding_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='driving_warning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='food_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='kidney_precaution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='liver_precaution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mechanism',
            field=models.TextField(blank=True, help_text='How it works'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='missed_dose_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pregnancy_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='serious_warning_signs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MedicineSafetyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('driving', 'Driving'), ('pregnancy', 'Pregnancy'), ('breastfeeding', 'Breastfeeding'), ('kidney', 'Kidney Conditions'), ('liver', 'Liver Conditions'), ('allergy', 'Allergies'), ('age', 'Age-Related Precautions'), ('interaction', 'Medicine Interactions'), ('duplicate', 'Duplicate Active Ingredients')], max_length=30)),
                ('status', models.CharField(choices=[('general_info', 'General Information'), ('low_concern', 'Low Concern'), ('caution', 'Caution'), ('important_warning', 'Important Warning'), ('review_required', 'Healthcare Review Required'), ('unavailable', 'Information Unavailable')], default='unavailable', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_notes', to='app.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'category')},
            },
        ),
    ]
