# Generated by Django 6.0.7 on 2026-07-26 14:02

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine_breastfeeding_info_medicine_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('needs_review', 'Needs Review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.prescription_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('engine', models.CharField(default='tesseract', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='app.prescriptionfile')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_name', models.CharField(blank=True, max_length=255)),
                ('detected_strength', models.CharField(blank=True, max_length=100)),
                ('detected_form', models.CharField(blank=True, max_length=100)),
                ('detected_frequency', models.CharField(blank=True, max_length=100)),
                ('detected_duration', models.CharField(blank=True, max_length=100)),
                ('ocr_confidence', models.FloatField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('matched_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.prescription')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
