import datetime

from django.core.management.base import BaseCommand

from app.models import MEDICINE, MedicineSafetyNote

REVIEWED = datetime.date(2026, 7, 1)
SOURCE = "General patient-information reference (public patient-leaflet / MedlinePlus-style summary, paraphrased for education)"

MEDICINES = [
    {
        "Medicine_name": "Paracetamol",
        "Generic_Name": "Acetaminophen",
        "Composition": "Paracetamol 500mg",
        "Indications": "Mild to moderate pain relief and fever reduction.",
        "Dosage": "Adults: 500mg-1000mg every 4-6 hours as needed, not exceeding 4000mg in 24 hours.",
        "Side_effects": "Generally well tolerated at recommended doses; rare allergic skin reactions.",
        "Precautions": "Do not exceed the maximum daily dose. Check other medicines for hidden paracetamol content.",
        "Drug_interactions": "Warfarin (increased bleeding risk with prolonged high-dose use), alcohol (increased liver strain).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Analgesic / Antipyretic",
        "prescription_required": False,
        "mechanism": "Reduces pain and fever, thought to act on pain and temperature-regulating centres; exact mechanism not fully established.",
        "food_guidance": "Can be taken with or without food.",
        "driving_warning": "Not known to affect driving or operating machinery at recommended doses.",
        "pregnancy_info": "Commonly used during pregnancy at recommended doses, but confirm with your doctor or pharmacist before use.",
        "breastfeeding_info": "Generally considered compatible with breastfeeding at recommended doses; confirm with a healthcare professional.",
        "kidney_precaution": "Dose adjustment or spacing between doses may be needed for people with reduced kidney function.",
        "liver_precaution": "Higher risk of liver damage in people with existing liver disease or heavy alcohol use; avoid exceeding recommended dose.",
        "storage_instructions": "Store below 25°C, away from moisture and direct sunlight, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered if using on a schedule; do not double up to make up for a missed dose.",
        "serious_warning_signs": "Signs of overdose (nausea, vomiting, abdominal pain) or allergic reaction (swelling, rash, difficulty breathing) require urgent medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "food": ("low_concern", "No significant food interaction is generally reported.", "No special action needed."),
            "liver": ("important_warning", "Overuse or use with heavy alcohol consumption can cause serious liver damage.", "Do not exceed the labelled dose. Tell your doctor about any liver condition or alcohol use."),
            "kidney": ("caution", "Reduced kidney function may require spacing doses further apart.", "Confirm dosing frequency with your doctor or pharmacist."),
            "pregnancy": ("low_concern", "Widely used in pregnancy at recommended doses in available general guidance.", "Confirm with your doctor or pharmacist before use."),
            "allergy": ("caution", "Rare allergic skin reactions have been reported.", "Stop use and seek medical advice if a rash or swelling develops."),
        },
    },
    {
        "Medicine_name": "Ibuprofen",
        "Generic_Name": "Ibuprofen",
        "Composition": "Ibuprofen 400mg",
        "Indications": "Pain relief, inflammation, and fever reduction.",
        "Dosage": "Adults: 200-400mg every 6-8 hours as needed, not exceeding 1200mg/day without medical advice.",
        "Side_effects": "Stomach upset, heartburn, nausea; long-term use may affect the stomach lining.",
        "Precautions": "Take with food. Avoid in active stomach ulcers unless directed by a doctor.",
        "Drug_interactions": "Aspirin, blood thinners (increased bleeding risk), other NSAIDs (increased side effects).",
        "Manufacturer": "Various generic manufacturers",
        "category": "NSAID (Anti-inflammatory)",
        "prescription_required": False,
        "mechanism": "Blocks enzymes involved in producing prostaglandins, reducing pain, inflammation, and fever.",
        "food_guidance": "Take with food or milk to reduce stomach irritation.",
        "driving_warning": "May rarely cause dizziness; avoid driving if affected.",
        "pregnancy_info": "Generally avoided, especially in the third trimester, unless specifically advised by a doctor.",
        "breastfeeding_info": "Considered generally compatible with breastfeeding in available general guidance; confirm with a healthcare professional.",
        "kidney_precaution": "Can reduce kidney function, especially with long-term use or existing kidney disease.",
        "liver_precaution": "Use with caution in people with liver disease; confirm with a doctor.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered if using on a schedule; skip if close to the next dose.",
        "serious_warning_signs": "Black or bloody stools, severe stomach pain, or signs of an allergic reaction require urgent medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "food": ("important_warning", "Can irritate the stomach lining, especially on an empty stomach.", "Take with food or milk."),
            "kidney": ("review_required", "May reduce kidney function, particularly with long-term use.", "Confirm the prescribed dose and duration with your doctor or pharmacist."),
            "pregnancy": ("important_warning", "Generally avoided in pregnancy, particularly the third trimester.", "Confirm with your doctor before use during pregnancy."),
            "liver": ("caution", "Use with caution if you have existing liver disease.", "Confirm with your doctor or pharmacist."),
            "interaction": ("caution", "Increased bleeding risk when combined with aspirin or other blood thinners.", "Tell your doctor or pharmacist about all medicines you take."),
        },
    },
    {
        "Medicine_name": "Amoxicillin",
        "Generic_Name": "Amoxicillin",
        "Composition": "Amoxicillin 500mg",
        "Indications": "Bacterial infections such as chest, ear, throat, and urinary tract infections.",
        "Dosage": "Adults: typically 250-500mg three times daily as prescribed; complete the full course.",
        "Side_effects": "Diarrhoea, nausea, skin rash.",
        "Precautions": "Complete the full course even if you feel better. Not effective against viral infections.",
        "Drug_interactions": "Methotrexate (increased toxicity), oral contraceptives (possible reduced effectiveness, use additional protection).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Antibiotic (Penicillin)",
        "prescription_required": True,
        "mechanism": "Interferes with bacterial cell wall formation, killing susceptible bacteria.",
        "food_guidance": "Can be taken with or without food.",
        "driving_warning": "Not known to affect driving or operating machinery.",
        "pregnancy_info": "Commonly used in pregnancy when clinically needed; confirm with your doctor.",
        "breastfeeding_info": "Generally considered compatible with breastfeeding; confirm with a healthcare professional.",
        "kidney_precaution": "Dose may need adjustment in people with significantly reduced kidney function.",
        "liver_precaution": "Used with caution in people with liver disease; confirm with a doctor.",
        "storage_instructions": "Store below 25°C; liquid forms may need refrigeration - check the label.",
        "missed_dose_guidance": "Take as soon as remembered unless it is nearly time for the next dose; do not double up.",
        "serious_warning_signs": "Severe allergic reaction (facial swelling, difficulty breathing, widespread rash) requires emergency care.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "allergy": ("important_warning", "Penicillin-type antibiotics can cause serious allergic reactions in sensitive individuals.", "Tell your doctor or pharmacist about any previous penicillin allergy before taking this medicine."),
            "pregnancy": ("low_concern", "Commonly used in pregnancy when clinically indicated.", "Confirm with your doctor before use."),
            "kidney": ("caution", "Dose may need adjustment with significantly reduced kidney function.", "Confirm the prescribed dose with your doctor or pharmacist."),
            "interaction": ("caution", "May reduce the effectiveness of hormonal contraceptives.", "Consider additional contraceptive precautions and confirm with your doctor or pharmacist."),
        },
    },
    {
        "Medicine_name": "Metformin",
        "Generic_Name": "Metformin Hydrochloride",
        "Composition": "Metformin 500mg",
        "Indications": "Management of type 2 diabetes to help control blood sugar levels.",
        "Dosage": "As prescribed by your doctor, typically starting at 500mg once or twice daily with food.",
        "Side_effects": "Nausea, diarrhoea, stomach discomfort, metallic taste, usually improving over time.",
        "Precautions": "Take with meals to reduce stomach upset. Regular kidney function monitoring is recommended.",
        "Drug_interactions": "Contrast dye used in some imaging scans (temporary stop may be advised), alcohol (increased risk of a rare but serious condition called lactic acidosis).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Antidiabetic (Biguanide)",
        "prescription_required": True,
        "mechanism": "Reduces glucose production by the liver and improves the body's sensitivity to insulin.",
        "food_guidance": "Take with or immediately after meals to reduce stomach upset.",
        "driving_warning": "Low risk of low blood sugar alone, but confirm with your doctor if combined with other diabetes medicines.",
        "pregnancy_info": "Used in some cases of diabetes in pregnancy under medical supervision; confirm with your doctor.",
        "breastfeeding_info": "Considered generally compatible with breastfeeding in available general guidance; confirm with a healthcare professional.",
        "kidney_precaution": "Requires dose adjustment or may need to be stopped in people with reduced kidney function.",
        "liver_precaution": "Avoided or used with caution in significant liver disease due to increased risk of a rare condition called lactic acidosis.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered with food unless close to the next dose; do not double up.",
        "serious_warning_signs": "Unusual muscle pain, difficulty breathing, stomach pain, or feeling very unwell can rarely indicate a serious condition requiring urgent care.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "kidney": ("review_required", "Requires dose adjustment or may need to be stopped depending on kidney function.", "Confirm your kidney function monitoring schedule with your doctor."),
            "liver": ("caution", "Used with caution in significant liver disease.", "Confirm with your doctor if you have a liver condition."),
            "food": ("low_concern", "Taking with food reduces stomach upset.", "Take with or after meals."),
            "interaction": ("caution", "Contrast dye used in some scans may require a temporary pause in this medicine.", "Tell the imaging department and your doctor that you take this medicine before any scan involving contrast dye."),
        },
    },
    {
        "Medicine_name": "Atorvastatin",
        "Generic_Name": "Atorvastatin Calcium",
        "Composition": "Atorvastatin 20mg",
        "Indications": "Lowering high cholesterol and reducing cardiovascular risk.",
        "Dosage": "As prescribed by your doctor, typically 10-80mg once daily, usually in the evening.",
        "Side_effects": "Muscle aches, headache, digestive upset.",
        "Precautions": "Report unexplained muscle pain or weakness promptly.",
        "Drug_interactions": "Grapefruit juice (increased drug levels), certain antibiotics and antifungals (increased side-effect risk).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Statin (Lipid-lowering)",
        "prescription_required": True,
        "mechanism": "Blocks an enzyme involved in cholesterol production in the liver, lowering LDL ('bad') cholesterol.",
        "food_guidance": "Avoid large quantities of grapefruit juice, which can increase drug levels in the body.",
        "driving_warning": "Not known to affect driving or operating machinery.",
        "pregnancy_info": "Not recommended during pregnancy; confirm alternative options with your doctor.",
        "breastfeeding_info": "Generally not recommended while breastfeeding; confirm with your doctor.",
        "kidney_precaution": "Generally used with standard monitoring; confirm with your doctor if kidney function is reduced.",
        "liver_precaution": "Requires liver function monitoring; avoided in active liver disease.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered unless it is nearly time for the next dose; do not double up.",
        "serious_warning_signs": "Unexplained muscle pain, tenderness, or weakness, especially with fever or dark urine, requires urgent medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "liver": ("review_required", "Requires periodic liver function monitoring.", "Attend scheduled liver function tests as advised by your doctor."),
            "pregnancy": ("important_warning", "Not recommended during pregnancy.", "Discuss alternative options with your doctor if pregnant or planning pregnancy."),
            "food": ("caution", "Grapefruit juice can increase drug levels and side-effect risk.", "Avoid large quantities of grapefruit juice."),
            "interaction": ("caution", "Certain antibiotics and antifungal medicines can increase side-effect risk.", "Tell your doctor or pharmacist about all medicines you take."),
        },
    },
    {
        "Medicine_name": "Omeprazole",
        "Generic_Name": "Omeprazole",
        "Composition": "Omeprazole 20mg",
        "Indications": "Acid reflux, heartburn, and stomach ulcer management.",
        "Dosage": "Adults: typically 20mg once daily, before a meal, as directed.",
        "Side_effects": "Headache, stomach pain, nausea, diarrhoea or constipation.",
        "Precautions": "Long-term use should be reviewed periodically with your doctor.",
        "Drug_interactions": "Clopidogrel (possible reduced effectiveness), certain antifungals (altered absorption).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Proton Pump Inhibitor",
        "prescription_required": False,
        "mechanism": "Reduces the amount of acid produced by the stomach lining.",
        "food_guidance": "Best taken before a meal, typically in the morning.",
        "driving_warning": "Not known to affect driving or operating machinery.",
        "pregnancy_info": "May be used in pregnancy when clinically needed; confirm with your doctor.",
        "breastfeeding_info": "Considered generally compatible with breastfeeding in available general guidance; confirm with a healthcare professional.",
        "kidney_precaution": "Generally used with standard monitoring; confirm with your doctor if kidney function is significantly reduced.",
        "liver_precaution": "Dose adjustment may be needed in significant liver disease.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered unless close to the next dose; do not double up.",
        "serious_warning_signs": "Difficulty swallowing, unexplained weight loss, or vomiting blood require prompt medical review.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "liver": ("caution", "Dose adjustment may be needed in significant liver disease.", "Confirm with your doctor if you have a liver condition."),
            "interaction": ("caution", "May reduce the effectiveness of clopidogrel, a blood-thinning medicine.", "Tell your doctor or pharmacist if you take clopidogrel."),
            "food": ("low_concern", "Best taken before a meal for optimal effect.", "Take roughly 30-60 minutes before eating."),
        },
    },
    {
        "Medicine_name": "Cetirizine",
        "Generic_Name": "Cetirizine Hydrochloride",
        "Composition": "Cetirizine 10mg",
        "Indications": "Relief of allergy symptoms such as hay fever, itching, and hives.",
        "Dosage": "Adults: 10mg once daily.",
        "Side_effects": "Drowsiness (less common than older antihistamines), dry mouth, headache.",
        "Precautions": "Use caution if drowsiness occurs.",
        "Drug_interactions": "Alcohol and other sedating medicines (may increase drowsiness).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Antihistamine",
        "prescription_required": False,
        "mechanism": "Blocks histamine receptors, reducing allergic symptoms such as itching, sneezing, and hives.",
        "food_guidance": "Can be taken with or without food.",
        "driving_warning": "May cause drowsiness in some people; use caution when driving until you know how it affects you.",
        "pregnancy_info": "Used in some cases under medical guidance; confirm with your doctor before use in pregnancy.",
        "breastfeeding_info": "Considered generally compatible with breastfeeding in available general guidance; confirm with a healthcare professional.",
        "kidney_precaution": "Dose adjustment may be needed with reduced kidney function.",
        "liver_precaution": "Dose adjustment may be needed with significant liver impairment.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered if using on a schedule; skip if close to the next dose.",
        "serious_warning_signs": "Signs of a severe allergic reaction (swelling of the face or throat, difficulty breathing) require emergency care.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "driving": ("caution", "May cause drowsiness in some individuals, although less commonly than older antihistamines.", "Avoid driving or operating machinery until you know how this medicine affects you."),
            "kidney": ("caution", "Dose adjustment may be needed with reduced kidney function.", "Confirm the appropriate dose with your doctor or pharmacist."),
            "pregnancy": ("caution", "Use in pregnancy should be confirmed with a doctor.", "Discuss with your doctor before use during pregnancy."),
        },
    },
    {
        "Medicine_name": "Aspirin",
        "Generic_Name": "Acetylsalicylic Acid",
        "Composition": "Aspirin 75mg",
        "Indications": "Low-dose: prevention of blood clots in people at risk. Higher dose: pain and fever relief.",
        "Dosage": "As prescribed; low-dose (75mg) is typically once daily for cardiovascular protection.",
        "Side_effects": "Stomach irritation, increased bleeding tendency.",
        "Precautions": "Not recommended for children under 16 due to risk of Reye's syndrome. Take with food.",
        "Drug_interactions": "Other blood thinners and NSAIDs (increased bleeding risk).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Antiplatelet / NSAID",
        "prescription_required": False,
        "mechanism": "Reduces the stickiness of platelets, helping prevent blood clot formation; also reduces pain and inflammation at higher doses.",
        "food_guidance": "Take with food to reduce stomach irritation.",
        "driving_warning": "Not known to affect driving or operating machinery.",
        "pregnancy_info": "Low-dose use may be advised in specific pregnancy conditions under medical supervision; confirm with your doctor. Higher doses are generally avoided, especially in the third trimester.",
        "breastfeeding_info": "Confirm with your doctor before use while breastfeeding.",
        "kidney_precaution": "Use with caution in reduced kidney function; confirm with your doctor.",
        "liver_precaution": "Use with caution in liver disease; confirm with your doctor.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered unless close to the next dose; do not double up.",
        "serious_warning_signs": "Signs of unusual bleeding or bruising, black stools, or vomiting blood require urgent medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "interaction": ("important_warning", "Combining with other blood thinners or NSAIDs increases bleeding risk.", "Tell your doctor or pharmacist about all medicines you take before combining."),
            "food": ("caution", "Can irritate the stomach lining.", "Take with food."),
            "pregnancy": ("review_required", "Use in pregnancy depends on dose and specific medical circumstances.", "Confirm with your doctor before use during pregnancy."),
            "age": ("important_warning", "Not recommended for children under 16 due to the risk of a rare but serious condition (Reye's syndrome).", "Do not give to children under 16 unless specifically directed by a doctor."),
        },
    },
    {
        "Medicine_name": "Azithromycin",
        "Generic_Name": "Azithromycin",
        "Composition": "Azithromycin 500mg",
        "Indications": "Bacterial infections including respiratory, skin, and some sexually transmitted infections.",
        "Dosage": "As prescribed, commonly 500mg once daily for 3 days, or as directed.",
        "Side_effects": "Nausea, diarrhoea, stomach pain.",
        "Precautions": "Complete the full course even if symptoms improve.",
        "Drug_interactions": "Certain heart-rhythm medicines and antacids (reduced absorption if taken together).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Antibiotic (Macrolide)",
        "prescription_required": True,
        "mechanism": "Stops bacteria from producing proteins they need to grow and multiply.",
        "food_guidance": "Can generally be taken with or without food; follow the specific product label.",
        "driving_warning": "Not known to affect driving or operating machinery.",
        "pregnancy_info": "Used in some cases under medical guidance; confirm with your doctor.",
        "breastfeeding_info": "Considered generally compatible with breastfeeding in available general guidance; confirm with a healthcare professional.",
        "kidney_precaution": "Generally used with standard monitoring; confirm with your doctor if kidney function is significantly reduced.",
        "liver_precaution": "Used with caution in liver disease; confirm with your doctor.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered unless close to the next dose; do not double up.",
        "serious_warning_signs": "Irregular heartbeat, severe diarrhoea, or signs of an allergic reaction require prompt medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "interaction": ("caution", "May interact with certain heart-rhythm medicines and antacids.", "Tell your doctor or pharmacist about all medicines you take."),
            "liver": ("caution", "Used with caution in people with liver disease.", "Confirm with your doctor if you have a liver condition."),
            "allergy": ("caution", "Allergic reactions are possible, particularly in those with prior macrolide antibiotic allergy.", "Tell your doctor about any previous antibiotic allergies."),
        },
    },
    {
        "Medicine_name": "Losartan",
        "Generic_Name": "Losartan Potassium",
        "Composition": "Losartan 50mg",
        "Indications": "High blood pressure management and kidney protection in some conditions.",
        "Dosage": "As prescribed by your doctor, typically 50-100mg once daily.",
        "Side_effects": "Dizziness, tiredness, higher potassium levels.",
        "Precautions": "Rise slowly from sitting or lying down to reduce dizziness.",
        "Drug_interactions": "Potassium supplements and certain diuretics (risk of high potassium levels), NSAIDs (reduced effectiveness).",
        "Manufacturer": "Various generic manufacturers",
        "category": "Angiotensin Receptor Blocker (ARB)",
        "prescription_required": True,
        "mechanism": "Blocks the action of a hormone (angiotensin II) that narrows blood vessels, helping lower blood pressure.",
        "food_guidance": "Can be taken with or without food.",
        "driving_warning": "May cause dizziness, particularly when starting treatment; use caution when driving until you know how it affects you.",
        "pregnancy_info": "Not recommended during pregnancy; confirm alternative options with your doctor promptly if pregnant.",
        "breastfeeding_info": "Generally not recommended while breastfeeding; confirm with your doctor.",
        "kidney_precaution": "Requires kidney function monitoring, particularly when starting or adjusting the dose.",
        "liver_precaution": "Dose adjustment may be needed in significant liver disease.",
        "storage_instructions": "Store below 25°C, away from moisture, out of reach of children.",
        "missed_dose_guidance": "Take as soon as remembered unless close to the next dose; do not double up.",
        "serious_warning_signs": "Fainting, severe dizziness, or swelling of the face or throat require urgent medical attention.",
        "source_reference": SOURCE,
        "last_reviewed": REVIEWED,
        "notes": {
            "kidney": ("review_required", "Requires kidney function and potassium level monitoring.", "Attend scheduled blood tests as advised by your doctor."),
            "pregnancy": ("important_warning", "Not recommended during pregnancy.", "Contact your doctor promptly if you are or may be pregnant."),
            "driving": ("caution", "May cause dizziness, especially when starting treatment.", "Use caution when driving until you know how this medicine affects you."),
            "interaction": ("caution", "Potassium supplements or certain diuretics can raise potassium levels; NSAIDs may reduce effectiveness.", "Tell your doctor or pharmacist about all medicines and supplements you take."),
        },
    },
]


class Command(BaseCommand):
    help = "Seed the database with sample medicine records and safety notes for development."

    def handle(self, *args, **options):
        created_count = 0
        for entry in MEDICINES:
            notes = entry.pop("notes")
            medicine, created = MEDICINE.objects.update_or_create(
                Medicine_name=entry["Medicine_name"],
                defaults=entry,
            )
            entry["notes"] = notes  # restore for idempotent re-runs
            if created:
                created_count += 1

            for category, (status, explanation, action) in notes.items():
                MedicineSafetyNote.objects.update_or_create(
                    medicine=medicine,
                    category=category,
                    defaults={
                        "status": status,
                        "explanation": explanation,
                        "recommended_action": action,
                        "source_reference": SOURCE,
                        "reviewed_date": REVIEWED,
                    },
                )

        self.stdout.write(self.style.SUCCESS(
            f"Seeded {len(MEDICINES)} medicines ({created_count} newly created), with safety notes."
        ))
